site_name: Illiterate
site_url: https://gaspect.github.io/pylliterate
repo_url: https://github.com/gaspect/pylliterate

theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: black
        accent: black

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences

nav:
    - Home: index.md
    - API: 
        pylliterate: pylliterate/__init__.md
        pylliterate.core: pylliterate/core.md
        pylliterate.config: pylliterate/config.md
        pylliterate.cli: pylliterate/cli.md
        pylliterate.main: pylliterate/__main__.md
